
//Symbol enumberation definition


public enum Symbol{
	EOF,
	//punctuation
	PERIOD,COMMA,SEMICOLON,
	//operators
	ASSIGN,EQ,NE,LT,GT,LE,GE,PLUS,MINUS,TIMES,SLASH,LPAREN,RPAREN,LCURLY,RCURLY,AMPERSAND,
	//keywords
	SOURCE,FUNCTION,RETURN,MAIN,IF,ELSE,WHILE,PRINT,ASINT,READLINE,CONS,HEAD,TAIL,NULL,
	//ID, integer,string
	ID,INTEGER,STRING
}

